name: eerie
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - audioread=2.1.8=py37hc8dfbb8_2
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=hd408876_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py37h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h211956c_0
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libflac=1.3.3=he1b5a44_0
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1006
  - libllvm8=8.0.1=hc9558a2_0
  - libogg=1.3.2=h516909a_1002
  - libpng=1.6.37=hbc83047_0
  - librosa=0.7.2=py_0
  - libsndfile=1.0.28=he1b5a44_1000
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.6=he1b5a44_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.31.0=py37h5202443_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.2=py37h4fdacc2_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - musdb=0.3.1=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.3=py37_0
  - numba=0.48.0=py37hb3f55d8_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.3=py37h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h049681c_0
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pyaml=19.4.1=py_0
  - pycparser=2.20=py_0
  - pydot=1.4.1=py37_0
  - pydub=0.23.1=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - pysoundfile=0.10.2=py_1001
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-dotenv=0.13.0=pyh9f0ad1d_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.5.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.3=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - resampy=0.2.2=py_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.14.0=py37_0
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - stempeg=0.1.8=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - torchaudio=0.5.0=py37
  - torchvision=0.6.0=py37_cu101
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.4=h516909a_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - cachetools==4.1.0
    - future==0.18.2
    - google-auth==1.15.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.29.0
    - markdown==3.2.2
    - museval==0.3.0
    - nonechucks==0.4.0
    - oauthlib==3.1.0
    - protobuf==3.12.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - simplejson==3.17.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - werkzeug==1.0.1
prefix: /home/romerogudw/anaconda3/envs/eerie

